content = open('templates/store/product_list.html').read()
content = content.replace("sort_by=='newest'", "sort_by == 'newest'")
content = content.replace("sort_by=='price_low'", "sort_by == 'price_low'")
content = content.replace("sort_by=='price_high'", "sort_by == 'price_high'")
content = content.replace("sort_by=='rating'", "sort_by == 'rating'")
content = content.replace("sort_by=='popular'", "sort_by == 'popular'")
content = content.replace("sort_by=='discount'", "sort_by == 'discount'")
open('templates/store/product_list.html', 'w').write(content)
print('Fixed!')
